export const ALUNO_SIGNIN_REQUEST = 'ALUNO_SIGNIN_REQUEST'
export const ALUNO_SIGNIN_SUCCESS = 'ALUNO_SIGNIN_SUCCESS'
export const ALUNO_SIGNIN_FAIL = 'ALUNO_SIGNIN_FAIL'

export const ALUNO_FIND_REQUEST = 'ALUNO_FIND_REQUEST'
export const ALUNO_FIND_SUCCESS = 'ALUNO_FIND_SUCCESS'
export const ALUNO_FIND_FAIL = 'ALUNO_FIND_FAIL'

export const ALUNO_NOTA_CREATE_REQUEST = 'ALUNO_NOTA_CREATE_REQUEST'
export const ALUNO_NOTA_CREATE_SUCCESS = 'ALUNO_NOTA_CREATE_SUCCESS'
export const ALUNO_NOTA_CREATE_FAIL = 'ALUNO_NOTA_CREATE_FAIL'
export const ALUNO_NOTA_CREATE_RESET = 'ALUNO_NOTA_CREATE_RESET'


export const ALUNO_NOTA_DETAILS_REQUEST = 'ALUNO_NOTA_DETAILS_REQUEST'
export const ALUNO_NOTA_DETAILS_SUCCESS = 'ALUNO_NOTA_DETAILS_SUCCESS'
export const ALUNO_NOTA_DETAILS_FAIL = 'ALUNO_NOTA_DETAILS_FAIL'
export const ALUNO_NOTA_DETAILS_RESET = 'ALUNO_NOTA_DETAILS_RESET'

export const ALUNO_NOTA_UPDATE_REQUEST = 'ALUNO_NOTA_UPDATE_REQUEST'
export const ALUNO_NOTA_UPDATE_SUCCESS = 'ALUNO_NOTA_UPDATE_SUCCESS'
export const ALUNO_NOTA_UPDATE_FAIL = 'ALUNO_NOTA_UPDATE_FAIL'
export const ALUNO_NOTA_UPDATE_RESET = 'ALUNO_NOTA_UPDATE_RESET'

export const ALUNO_NOTA_DELETE_REQUEST = 'ALUNO_NOTA_DELETE_REQUEST'
export const ALUNO_NOTA_DELETE_SUCCESS = 'ALUNO_NOTA_DELETE_SUCCESS'
export const ALUNO_NOTA_DELETE_FAIL = 'ALUNO_NOTA_DELETE_FAIL'
export const ALUNO_NOTA_DELETE_RESET = 'ALUNO_NOTA_DELETE_RESET'