export const ASSINATURA_CREATE_REQUEST = 'ASSINATURA_CREATE_REQUEST';
export const ASSINATURA_CREATE_SUCCESS = 'ASSINATURA_CREATE_SUCCESS';
export const ASSINATURA_CREATE_FAIL = 'ASSINATURA_CREATE_FAIL';
export const ASSINATURA_CREATE_RESET = 'ASSINATURA_CREATE_RESET';

export const ASSINATURA_PAY_REQUEST = 'ASSINATURA_PAY_REQUEST';
export const ASSINATURA_PAY_SUCCESS = 'ASSINATURA_PAY_SUCCESS';
export const ASSINATURA_PAY_FAIL = 'ASSINATURA_PAY_FAIL';
export const ASSINATURA_PAY_RESET = 'ASSINATURA_PAY_RESET';

export const ASSINATURA_DETAILS_REQUEST = 'ASSINATURA_DETAILS_REQUEST';
export const ASSINATURA_DETAILS_SUCCESS = 'ASSINATURA_DETAILS_SUCCESS';
export const ASSINATURA_DETAILS_FAIL = 'ASSINATURA_DETAILS_FAIL';