export const AULA_FIND_REQUEST = 'AULA_FIND_REQUEST'
export const AULA_FIND_SUCCESS = 'AULA_FIND_SUCCESS'
export const AULA_FIND_FAIL = 'AULA_FIND_FAIL'

export const AULA_DELETE_REQUEST = 'AULA_DELETE_REQUEST'
export const AULA_DELETE_SUCCESS = 'AULA_DELETE_SUCCESS'
export const AULA_DELETE_FAIL = 'AULA_DELETE_FAIL'
export const AULA_DELETE_RESET = 'AULA_DELETE_RESET'

export const AULA_CREATE_REQUEST = 'AULA_CREATE_REQUEST'
export const AULA_CREATE_SUCCESS = 'AULA_CREATE_SUCCESS'
export const AULA_CREATE_FAIL = 'AULA_CREATE_FAIL'
export const AULA_CREATE_RESET = 'AULA_CREATE_RESET'