export const AULA_FIND_REQUEST = 'AULA_FIND_REQUEST'
export const AULA_FIND_SUCCESS = 'AULA_FIND_SUCCESS'
export const AULA_FIND_FAIL = 'AULA_FIND_FAIL'

export const AULA_DELETE_REQUEST = 'AULA_DELETE_REQUEST'
export const AULA_DELETE_SUCCESS = 'AULA_DELETE_SUCCESS'
export const AULA_DELETE_FAIL = 'AULA_DELETE_FAIL'
export const AULA_DELETE_RESET = 'AULA_DELETE_RESET'

export const AULA_CREATE_REQUEST = 'AULA_CREATE_REQUEST'
export const AULA_CREATE_SUCCESS = 'AULA_CREATE_SUCCESS'
export const AULA_CREATE_FAIL = 'AULA_CREATE_FAIL'
export const AULA_CREATE_RESET = 'AULA_CREATE_RESET'

export const AULA_DETAILS_REQUEST = 'AULA_DETAILS_REQUEST'
export const AULA_DETAILS_SUCCESS = 'AULA_DETAILS_SUCCESS'
export const AULA_DETAILS_FAIL = 'AULA_DETAILS_FAIL'
export const AULA_DETAILS_RESET = 'AULA_DETAILS_RESET'

export const AULA_UPDATE_REQUEST = 'AULA_UPDATE_REQUEST'
export const AULA_UPDATE_SUCCESS = 'AULA_UPDATE_SUCCESS'
export const AULA_UPDATE_FAIL = 'AULA_UPDATE_FAIL'
export const AULA_UPDATE_RESET = 'AULA_UPDATE_RESET'

export const AULA_INFO_LIST_REQUEST = 'AULA_INFO_LIST_REQUEST'
export const AULA_INFO_LIST_SUCCESS = 'AULA_INFO_LIST_SUCCESS'
export const AULA_INFO_LIST_FAIL = 'AULA_INFO_LIST_FAIL'
export const AULA_INFO_LIST_RESET = 'AULA_INFO_LIST_RESET'

export const AULA_INFORMATIONS_REQUEST = 'AULA_INFORMATIONS_REQUEST'
export const AULA_INFORMATIONS_SUCCESS = 'AULA_INFORMATIONS_SUCCESS'
export const AULA_INFORMATIONS_FAIL = 'AULA_INFORMATIONS_FAIL'
export const AULA_INFORMATIONS_RESET = 'AULA_INFORMATIONS_RESET'

export const AULA_FINISH_REQUEST = 'AULA_FINISH_REQUEST'
export const AULA_FINISH_SUCCESS = 'AULA_FINISH_SUCCESS'
export const AULA_FINISH_FAIL = 'AULA_FINISH_FAIL'
export const AULA_FINISH_RESET = 'AULA_FINISH_RESET'