export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_FILTER_REQUEST = 'CURSO_FILTER_REQUEST'
export const CURSO_FILTER_SUCCESS = 'CURSO_FILTER_SUCCESS'
export const CURSO_FILTER_FAIL = 'CURSO_FILTER_FAIL'