export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_FIND_REQUEST = 'CURSO_FIND_REQUEST'
export const CURSO_FIND_SUCCESS = 'CURSO_FIND_SUCCESS'
export const CURSO_FIND_FAIL = 'CURSO_FIND_FAIL'

export const CURSO_PROFESSOR_REQUEST = 'CURSO_PROFESSOR_REQUEST'
export const CURSO_PROFESSOR_SUCCESS = 'CURSO_PROFESSOR_SUCCESS'
export const CURSO_PROFESSOR_FAIL = 'CURSO_PROFESSOR_FAIL'

export const CURSO_CREATE_REQUEST = 'CURSO_CREATE_REQUEST'
export const CURSO_CREATE_SUCCESS = 'CURSO_CREATE_SUCCESS'
export const CURSO_CREATE_FAIL = 'CURSO_CREATE_FAIL'
export const CURSO_CREATE_RESET = 'CURSO_CREATE_RESET'

export const CURSO_DETAILS_REQUEST = 'CURSO_DETAILS_REQUEST'
export const CURSO_DETAILS_SUCCESS = 'CURSO_DETAILS_SUCCESS'
export const CURSO_DETAILS_FAIL = 'CURSO_DETAILS_FAIL'
export const CURSO_DETAILS_RESET = 'CURSO_DETAILS_RESET'

export const CURSO_UPDATE_REQUEST = 'CURSO_UPDATE_REQUEST'
export const CURSO_UPDATE_SUCCESS = 'CURSO_UPDATE_SUCCESS'
export const CURSO_UPDATE_FAIL = 'CURSO_UPDATE_FAIL'
export const CURSO_UPDATE_RESET = 'CURSO_UPDATE_RESET'

export const CURSO_DELETE_REQUEST = 'CURSO_DELETE_REQUEST'
export const CURSO_DELETE_SUCCESS = 'CURSO_DELETE_SUCCESS'
export const CURSO_DELETE_FAIL = 'CURSO_DELETE_FAIL'
export const CURSO_DELETE_RESET = 'CURSO_DELETE_RESET'

export const CURSO_INFORMATIONS_REQUEST = 'CURSO_INFORMATIONS_EQUEST'
export const CURSO_INFORMATIONS_SUCCESS = 'CURSO_INFORMATIONS_SUCCESS'
export const CURSO_INFORMATIONS_FAIL = 'CURSO_INFORMATIONS_FAIL'
export const CURSO_INFORMATIONS_RESET = 'CURSO_INFORMATIONS_RESET'

export const CURSO_MATRICULA_REQUEST = 'CURSO_MATRICULA_EQUEST'
export const CURSO_MATRICULA_SUCCESS = 'CURSO_MATRICULA_SUCCESS'
export const CURSO_MATRICULA_FAIL = 'CURSO_MATRICULA_FAIL'
export const CURSO_MATRICULA_RESET = 'CURSO_MATRICULA_RESET'

export const CURSO_AVALIACAO_DETAILS_REQUEST = 'CURSO_AVALIACAO_DETAILS_REQUEST'
export const CURSO_AVALIACAO_DETAILS_SUCCESS = 'CURSO_AVALIACAO_DETAILS_SUCCESS'
export const CURSO_AVALIACAO_DETAILS_FAIL = 'CURSO_AVALIACAO_DETAILS_FAIL'
export const CURSO_AVALIACAO_DETAILS_RESET = 'CURSO_AVALIACAO_DETAILS_RESET'

export const CURSO_AVALIACAO_SAVE_REQUEST = 'CURSO_AVALIACAO_SAVE_REQUEST'
export const CURSO_AVALIACAO_SAVE_SUCCESS = 'CURSO_AVALIACAO_SAVE_SUCCESS'
export const CURSO_AVALIACAO_SAVE_FAIL = 'CURSO_AVALIACAO_SAVE_FAIL'
export const CURSO_AVALIACAO_SAVE_RESET = 'CURSO_AVALIACAO_SAVE_RESET'
export const CURSO_AVALIACAO_DETAILS_EMPTY = 'CURSO_AVALIACAO_DETAILS_EMPTY'