export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_FIND_REQUEST = 'CURSO_FIND_REQUEST'
export const CURSO_FIND_SUCCESS = 'CURSO_FIND_SUCCESS'
export const CURSO_FIND_FAIL = 'CURSO_FIND_FAIL'