export const MATRICULA_FIND_REQUEST = 'MATRICULA_FIND_EQUEST'
export const MATRICULA_FIND_SUCCESS = 'MATRICULA_FIND_SUCCESS'
export const MATRICULA_FIND_FAIL = 'MATRICULA_FIND_FAIL'
export const MATRICULA_FIND_RESET = 'MATRICULA_FIND_RESET'

export const MATRICULA_CREATE_REQUEST = 'MATRICULA_CREATE_EQUEST'
export const MATRICULA_CREATE_SUCCESS = 'MATRICULA_CREATE_SUCCESS'
export const MATRICULA_CREATE_FAIL = 'MATRICULA_CREATE_FAIL'
export const MATRICULA_CREATE_RESET = 'MATRICULA_CREATE_RESET'

export const MATRICULA_DELETE_REQUEST = 'MATRICULA_DELETE_EQUEST'
export const MATRICULA_DELETE_SUCCESS = 'MATRICULA_DELETE_SUCCESS'
export const MATRICULA_DELETE_FAIL = 'MATRICULA_DELETE_FAIL'
export const MATRICULA_DELETE_RESET = 'MATRICULA_DELETE_RESET'
