export const POST_FIND_REQUEST = 'POST_FIND_REQUEST'
export const POST_FIND_SUCCESS = 'POST_FIND_SUCCESS'
export const POST_FIND_FAIL = 'POST_FIND_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'

export const POST_INFORMATIONS_REQUEST = 'POST_INFORMATIONS_REQUEST'
export const POST_INFORMATIONS_SUCCESS = 'POST_INFORMATIONS_SUCCESS'
export const POST_INFORMATIONS_FAIL = 'POST_INFORMATIONS_FAIL'
export const POST_INFORMATIONS_RESET = 'POST_INFORMATIONS_RESET'

export const POST_RESPONSE_LIST_REQUEST = 'POST_RESPONSE_LIST_REQUEST'
export const POST_RESPONSE_LIST_SUCCESS = 'POST_RESPONSE_LIST_SUCCESS'
export const POST_RESPONSE_LIST_FAIL = 'POST_RESPONSE_LIST_FAIL'
export const POST_RESPONSE_LIST_RESET = 'POST_RESPONSE_LIST_RESET'

export const POST_SAVE_RESPONSE_REQUEST = 'POST_SAVE_RESPONSE_REQUEST'
export const POST_SAVE_RESPONSE_SUCCESS = 'POST_SAVE_RESPONSE_SUCCESS'
export const POST_SAVE_RESPONSE_FAIL = 'POST_SAVE_RESPONSE_FAIL'
export const POST_SAVE_RESPONSE_RESET = 'POST_SAVE_RESPONSE_RESET'

export const POST_SOLUTION_REQUEST = 'POST_SOLUTION_REQUEST'
export const POST_SOLUTION_SUCCESS = 'POST_SOLUTION_SUCCESS'
export const POST_SOLUTION_FAIL = 'POST_SOLUTION_FAIL'
export const POST_SOLUTION_RESET = 'POST_SOLUTION_RESET'