export const POST_FIND_REQUEST = 'POST_FIND_REQUEST'
export const POST_FIND_SUCCESS = 'POST_FIND_SUCCESS'
export const POST_FIND_FAIL = 'POST_FIND_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'