export const PROFESSOR_SIGNIN_REQUEST = 'PROFESSOR_SIGNIN_REQUEST'
export const PROFESSOR_SIGNIN_SUCCESS = 'PROFESSOR_SIGNIN_SUCCESS'
export const PROFESSOR_SIGNIN_FAIL = 'PROFESSOR_SIGNIN_FAIL'

export const PROFESSOR_SIGNOUT = 'PROFESSOR_SIGNOUT'

export const PROFESSOR_ASSIGNMENTS_REQUEST = 'PROFESSOR_ASSIGNMENTS_REQUEST'
export const PROFESSOR_ASSIGNMENTS_SUCCESS = 'PROFESSOR_ASSIGNMENTS_SUCCESS'
export const PROFESSOR_ASSIGNMENTS_FAIL = 'PROFESSOR_ASSIGNMENTS_FAIL'

export const PROFESSOR_DETAILS_REQUEST = 'PROFESSOR_DETAILS_REQUEST'
export const PROFESSOR_DETAILS_SUCCESS = 'PROFESSOR_DETAILS_SUCCESS'
export const PROFESSOR_DETAILS_FAIL = 'PROFESSOR_DETAILS_FAIL'
export const PROFESSOR_DETAILS_RESET = 'PROFESSOR_DETAILS_RESET'

export const PROFESSOR_UPDATE_PROFILE_REQUEST = 'PROFESSOR_UPDATE_PROFILE_REQUEST';
export const PROFESSOR_UPDATE_PROFILE_SUCCESS = 'PROFESSOR_UPDATE_PROFILE_SUCCESS';
export const PROFESSOR_UPDATE_PROFILE_FAIL = 'PROFESSOR_UPDATE_PROFILE_FAIL';
export const PROFESSOR_UPDATE_PROFILE_RESET = 'PROFESSOR_UPDATE_PROFILE_RESET';
