export const PROFESSOR_SIGNIN_REQUEST = 'PROFESSOR_SIGNIN_REQUEST'
export const PROFESSOR_SIGNIN_SUCCESS = 'PROFESSOR_SIGNIN_SUCCESS'
export const PROFESSOR_SIGNIN_FAIL = 'PROFESSOR_SIGNIN_FAIL'

export const PROFESSOR_SIGNOUT = 'PROFESSOR_SIGNOUT'